### ISSUE TITLE
Legal: Add CLA

### ISSUE THREAD

**Issue by cfanoulis** [dirigeants/klasa-pieces#122]
As discussed in the Discord server, it should be good to add a CLA to make sure permission is granted by the package authors to distribute their work under the dirigenants name and copyright, with the MIT licence.

Accompanies https://github.com/dirigeants/klasa-pieces/pull/121

**Comment by UnseenFaith** [comment]
There is an explicit CLA given by Github TOS that all contributions to a repository are licensed under the same license of which the repository is licensed for, unless there is an agreement that supersedes it.

**Comment by cfanoulis** [comment]
closing as resolved
