### ISSUE TITLE
sqlite provider error errors

### ISSUE THREAD

**Issue by BannerBomb** [dirigeants/klasa-pieces#161]
First let me start by saying I am using the Master branch files latest commit

Hey, so with the `sqlite.js` provider I get this error `Error: The type 'messagepromise' is unavailable, please set its definition in the constructor.` and `Error: The type 'bigint' is unavailable, please set its definition in the constructor.` These errors only occur if I have
```js
Client.defaultClientSchema
	.add('restart', folder => folder
		.add('message', 'messagepromise')
		.add('timestamp', 'bigint', { min: 0 }))
```
defined in my index file. If I am doing something wrong what should I put it as? I never had this error on the other providers except the sqlite one.

The other error I get sometimes is also `Error: SQLITE_ERROR: near ".": syntax error` which it created a database but with empty keys in the tables.
![image](https://user-images.githubusercontent.com/11788894/49703032-edb91f80-fbcd-11e8-8151-e1e960bb66de.png)

**Comment by cfanoulis** [comment]
please install the serializers from the `serializers/` folder of **this** repo

**Comment by cfanoulis** [comment]
Just going to shove @kyranet into this, since settingsgateway is his invention, if I recall correctly
