### ISSUE TITLE
RethinkDB provider is "undefined".

### ISSUE THREAD

**Issue by MAPReiff** [dirigeants/klasa-pieces#169]
Ok, so I'm new to this and my stupidity is probably the cause of the issue, BUT....

I downloaded and added the Rethink provider from this repo, and when I boot my bot I get this error

`[2019-01-29 19:11:26] TypeError: Cannot read property 'rethinkdb' of undefined`
`[2019-01-29 19:11:26] /Users/mitchell/Desktop/M8-Bot/providers/rethinkdb.js`

Any ideas, I'm sorry if this is something really stupid.

**Comment by kyranet** [comment]
You need klasa master in order to run the providers

**Comment by MAPReiff** [comment]
> You need klasa master in order to run the providers

Thank you :P 
Like I said above, it was my stupidity.
