### ISSUE TITLE
Role Reaction

### ISSUE THREAD

**Issue by 3cmXD** [dirigeants/klasa-pieces#184]
hi,

Give a role when someone react to a message ID with the emoji ID

**Comment by bdistin** [comment]
Hi,

This is not the place to ask for support on how to do something.

**Comment by 3cmXD** [comment]
i know im sorry i just explained badly im just asking a reaction role like command

!addreaction #welcome (message ID) :emoji: @Member

**Comment by kyranet** [comment]
Role reactions can only be done with a combo of command and event (with partial emojis, otherwise raw events).

**Comment by 3cmXD** [comment]
oh i see but there no a simple way as monitor or something that isnt "user-friendly" so the modification are only into the code
