### ISSUE TITLE
Feature Request: MSSQL Provider

### ISSUE THREAD

**Issue by bdistin** [dirigeants/klasa-pieces#21]
I would like someone to help expand our official plugins to add support for Microsoft SQL databases. The Provider should of course be SGv2 compatible, as even those who are using klasa v0.4.0 will be able to use the up to date provider. (SGv2 Providers are backwards compatible with SGv1)

**Comment by kyranet** [comment]
For multi-platform support, we use the [Tedious](https://www.npmjs.com/package/tedious) wrapper, which is tedious.

- The code needed to write the SGv2-compatible Tedious provider is very hard to achieve without the presence of my previously proposed `GatewayORM`. Why is that? Well, if you check the documentation, to pass parameters you need to use some middleware that is uncompatible with the current state of SGv2, check it [here](http://tediousjs.github.io/tedious/parameters.html).
- Wrapping it is **very bloated** and **very hard**, why is that? It uses both events and callbacks (Promise support is lacking) althought it comes with many features.

Current code (if somebody wants to continue this):

```javascript
const { Provider } = require('klasa');
const { Connection } = require('tedious');

module.exports = class extends Provider {

	constructor(...args) {
		super(...args, {
			enabled: true,
			sql: true,
			description: 'Allows you to use MSSQL functionality throught Klasa'
		});
		this.db = null;
	}

	init() {
		return new Promise((resolve, reject) => {
			this.db = new Connection({
				userName: 'database-userName',
				password: 'database-password',
				server: '192.168.1.210',
				// If you're on Windows Azure, you will need this enabled:
				options: { encrypt: false }
			});

			this.db.on('connect', (error) => {
				if (error) reject(error);
				else resolve();
			});
		});
	}
}
```
