### ISSUE TITLE
Notice: Retraction of contributions

### ISSUE THREAD

**Issue by cfanoulis** [dirigeants/klasa-pieces#229]
Good evening. I'd like to notify you that I am retracting any and all licences I have provided along with my code in this repository

You are hereby given 24 hours to remove any code that I may have committed. After that time window, I reserve any and all legal rights that occur from copyright infringement.

For your convenience, you may see a list of my commits [here](https://github.com/dirigeants/klasa-pieces/commits?author=cfanoulis).

Signed,
Charalampos Fanoulis
yo@fanoulis.dev

**Comment by cfanoulis** [comment]
[del]

**Comment by bdistin** [comment]
For future reference: https://github.com/github/site-policy/blob/1263bf0164cfe60d0900e70ba9126855c7c23c6c/Policies/github-terms-of-service.md#6-contributions-under-repository-license

I just don't think you are worth fighting over.
