### ISSUE TITLE
Klasa.js.org is broken

### ISSUE THREAD

**Issue by Gabb-c** [dirigeants/klasa-pieces#234]
Cant see the documentation pages. Only shows this message:
![Screenshot from 2020-08-27 16-34-35](https://user-images.githubusercontent.com/65926741/91486901-4b4e3d80-e883-11ea-8b33-d89ea77e03dc.png)

**Comment by favna** [comment]
Klasa is dead. The new framework is [Sapphire](https://github.com/sapphire-project/framework). You can join the Discord invite through this link: https://discord.com/invite/j8ACK6u

**Comment by Gabb-c** [comment]
Oh, thanks Favna
