### ISSUE TITLE
Not playing playlists

### ISSUE THREAD

**Issue by Jason160** [dirigeants/klasa-pieces#27]
when i paste the playlist link it doesnt play it

**Comment by kyranet** [comment]
You could at least tell us which piece is failing, or write an actual issue (Is code modified? Does it show errors?)

**Comment by Jason160** [comment]
i

**Comment by Jason160** [comment]
when i send a command like 'play
https://www.youtube.com/playlist?list=PLAYmJphkYuTfkMez7xug3R6t9VOJU0iwS it
doesnt play anything im not a coder or anything so i cannot help you and it
is with the bot that you invite to your server

**Comment by kyranet** [comment]
We have no music command in this repository, in fact, we do not have any music commands, but in the [komada-pieces repo](https://github.com/dirigeants/komada-pieces/tree/master/commands/Music).
